export { default as sdglogo } from './sdglogo.svg'
export { default as sdgjr } from './sdgjr.svg'
export { default as techladies } from './techladies.png'
export { default as WomensTechNetwork } from './womens-tech-network-logo-square.png'
export { default as WWCTampa } from './WWCTampa.jpg'